version: '3'
services:
  web:
    container_name: web
    restart: always 
    build:
      context: .
      dockerfile: deploy/docker/nginx.Dockerfile
      args:
        # define these variables in `.env` file
        - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}
        - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - nginx_network
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: deploy/docker/web.Dockerfile
    expose:
      - 5000
    links:
    - redis
    volumes:
    - "${SAMPLES_DIR}:/mnt/samples"
    depends_on:
      - "redis"
      - "ursadb"
    networks:
      - nginx_network
  daemon:
    restart: always
    build:
      context: .
      dockerfile: deploy/docker/daemon.Dockerfile
    links:
    - redis
    - ursadb
    volumes:
    - "${SAMPLES_DIR}:/mnt/samples"
    depends_on:
      - "redis"
      - "ursadb"
    networks:
      - nginx_network
  ursadb:
    restart: always
    build:
      context: ursadb/
      dockerfile: Dockerfile
    ports:
    - "127.0.0.1:9281:9281"
    volumes:
    - "${SAMPLES_DIR}:/mnt/samples"
    - "${INDEX_DIR}:/var/lib/ursadb"
    networks:
      - nginx_network
  redis:
    restart: always
    image: redis
    networks:
      - nginx_network
    
networks:
  nginx_network:
    driver: bridge